In [ ]:
 from scipy.linalg import svd,qr
 import numpy as np
 import time

In [ ]:
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]]) #given array
A

array([[ 1, -2,  3, -3],
       [ 2, -4,  9, -2],
       [-3,  6, -9,  9]])

In [ ]:
np.linalg.matrix_rank(A) #rank of array

2

In [ ]:
s,v,r = svd(A) #Finding svd of A
s

array([[ 2.66235859e-01,  1.70641342e-01,  9.48683298e-01],
       [ 5.39615303e-01, -8.41911709e-01, -5.55111512e-17],
       [-7.98707576e-01, -5.11924025e-01,  3.16227766e-01]])

In [ ]:
v

array([1.78088115e+01, 4.22448020e+00, 3.71370969e-16])

In [ ]:
s@s.T.conjugate() #checking s is unitary

array([[1.00000000e+00, 1.23757111e-17, 1.72285197e-17],
       [1.23757111e-17, 1.00000000e+00, 1.99174924e-16],
       [1.72285197e-17, 1.99174924e-16, 1.00000000e+00]])

In [ ]:
s[:,:2] #taking first 2 coloumns

array([[ 0.26623586,  0.17064134],
       [ 0.5396153 , -0.84191171],
       [-0.79870758, -0.51192403]])

In [ ]:
a , b=qr(A)
a #calculating using qr

array([[-0.26726124,  0.95618289, -0.11952286],
       [-0.53452248, -0.04390192,  0.84401323],
       [ 0.80178373,  0.28945968,  0.52283453]])

In [ ]:
a[:,:2] #taking first 2 coloumns as rank is 2

array([[-0.26726124,  0.95618289],
       [-0.53452248, -0.04390192],
       [ 0.80178373,  0.28945968]])

In [ ]:
check = np.zeros((3,4)) #creating a matrix joining both
for i in range(4):
  if i<2:

    check[:,i] = s[:,i]
  else:

    check[:,i] = a[:,i-2]


In [ ]:
np.linalg.matrix_rank(check) #rank will be 2 if no truncation error as they have same span

3

In [ ]:
check

array([[ 0.26623586,  0.17064134, -0.26726124,  0.95618289],
       [ 0.5396153 , -0.84191171, -0.53452248, -0.04390192],
       [-0.79870758, -0.51192403,  0.80178373,  0.28945968]])

In [ ]:
 %timeit s,v,r=svd(A)

21.8 µs ± 2.57 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit a , b=qr(A) #svd method is faster

28 µs ± 916 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
