In [29]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],[4, 1, 9, 1, -9]])
A

array([[ 1, -2,  9,  5,  4],
       [ 1, -1,  6,  5, -3],
       [-2,  0, -6,  1, -2],
       [ 4,  1,  9,  1, -9]])

In [30]:
np.linalg.matrix_rank(A) #rank of matrix is 3

3

In [31]:
s,v,d = svd(A) #singular value decomposition

In [32]:
v

array([1.72083086e+01, 1.01450209e+01, 4.99526437e+00, 9.56282692e-16])

In [33]:
d.T

array([[ 0.24638127, -0.12991821,  0.3027347 , -0.87219483,  0.26466093],
       [-0.04503456, -0.20626881,  0.2022255 ,  0.3573579 ,  0.8870317 ],
       [ 0.8742475 ,  0.22905181,  0.3015276 ,  0.29073161, -0.08822031],
       [ 0.30107333,  0.27058334, -0.84037193, -0.14709627,  0.32905504],
       [-0.28690474,  0.90271499,  0.26516538, -0.07354813,  0.16452752]])

In [34]:
q,r=qr(A)

In [35]:
q1,r1 = qr(A.T)

In [36]:
q1

array([[-0.08873565, -0.07763996, -0.39411774,  0.57324869, -0.70862908],
       [ 0.1774713 , -0.01770736, -0.2316473 ,  0.68751498,  0.6647203 ],
       [-0.79862086, -0.1797978 , -0.48741131, -0.1910829 ,  0.23620969],
       [-0.44367825, -0.3881998 ,  0.72286651,  0.36021819, -0.01254537],
       [-0.3549426 ,  0.90035112,  0.17579809,  0.18010909, -0.00627268]])

In [37]:
r1

array([[-1.12694277e+01, -6.21149557e+00,  5.23540341e+00,
        -4.61425385e+00],
       [ 0.00000000e+00, -5.78077182e+00, -9.54835308e-01,
        -1.04378074e+01],
       [ 0.00000000e+00,  0.00000000e+00,  4.08397364e+00,
        -7.05413629e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.39728491e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [38]:
check = np.zeros((4,5)) #creating a matrix joining both
for i in range(4):
  if i<2:
    check[i,:] = d.T[3+i,:] #lasttwo rows of d transpose
  else:

    check[i,:] = q1[i+1,:] #last two rows of q1

In [39]:
check

array([[ 0.30107333,  0.27058334, -0.84037193, -0.14709627,  0.32905504],
       [-0.28690474,  0.90271499,  0.26516538, -0.07354813,  0.16452752],
       [-0.44367825, -0.3881998 ,  0.72286651,  0.36021819, -0.01254537],
       [-0.3549426 ,  0.90035112,  0.17579809,  0.18010909, -0.00627268]])

In [40]:
np.linalg.matrix_rank(check) #they are not same,as rank is 4

4