<a href="https://colab.research.google.com/github/sinancc/MA22C026_2023_PL/blob/main/Assignments/Assignment%205/Averaging_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def create_matrix(n, k):
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(max(0, i - k), min(n, i + k + 1)):
            A[i, j] = 1
    return A

In [ ]:
 create_matrix(15,4)

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.

In [ ]:
def averaging_operator(n,k):
  A=create_matrix(n,k)
  A /= np.sum(A,axis=1, keepdims=True)
  return A


In [ ]:
averaging_operator(15,4)

array([[0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
        0.16666667, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.14285714,
        0.14285714, 0.14285714, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.125     , 0.125     , 0.125     , 0.125     , 0.125     ,
        0.125     , 0.125     , 0.125     , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.        ,
        0.        , 0.        , 0.        , 

In [ ]:
import numpy as np
import math
n = 1000
k=200
x = np.linspace(0,10,n)
def function_value(x):
    return x**2 + 2 * np.sin(10 * x)

y= function_value(x)
A=averaging_operator(n,k)
np.dot(y,A)

array([ 0.85748926,  0.87234894,  0.88743286,  0.9026926 ,  0.91807897,
        0.93354255,  0.94903413,  0.9645053 ,  0.97990885,  0.99519929,
        1.01033333,  1.02527027,  1.03997243,  1.05440557,  1.06853918,
        1.08234683,  1.09580641,  1.1089004 ,  1.12161601,  1.13394531,
        1.14588535,  1.15743818,  1.16861081,  1.17941519,  1.18986804,
        1.19999074,  1.20980909,  1.21935308,  1.22865655,  1.23775691,
        1.24669474,  1.2555134 ,  1.26425859,  1.2729779 ,  1.28172036,
        1.29053592,  1.29947497,  1.30858785,  1.31792435,  1.32753319,
        1.33746157,  1.3477547 ,  1.35845531,  1.36960328,  1.38123523,
        1.39338415,  1.40607905,  1.41934474,  1.43320152,  1.44766504,
        1.4627461 ,  1.47845056,  1.49477929,  1.5117282 ,  1.52928823,
        1.54744546,  1.56618128,  1.58547257,  1.60529192,  1.62560792,
        1.6463855 ,  1.66758626,  1.68916884,  1.7110894 ,  1.73330202,
        1.75575916,  1.77841218,  1.80121179,  1.82410856,  1.84