<a href="https://colab.research.google.com/github/sinancc/MA22C026_2023_PL/blob/main/Assignments/Assignment%205/Row_Swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def swaprow(i, j, A):
  tmp = A[i, :]
  A[i, :] = A[j, :]
  A[j, :] = tmp
  return A
#this function is not doing row swap properly

In [2]:
import numpy as np

In [3]:
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
swaprow(1,2,A)
# validating our intution

array([[1, 2, 3],
       [7, 8, 9],
       [7, 8, 9]])

In [5]:
def swap_row_1(i,j,A):
  A[[i,j]]=A[[j,i]]
  return A
#Defining new function,which is accurate

In [6]:
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
swap_row_1(1,2,A)
#validating our new function is working

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])