<a href="https://colab.research.google.com/github/sinancc/MA22C026_2023_PL/blob/main/Assignments/Assignment%204/numpy_blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array vs List

In [77]:
import numpy as np
import math

In [78]:
A = [0.1, 1.3, 0.4, 0.5] # list
a = np.array(A) # numpy array
type(a), type(A)

(numpy.ndarray, list)

In [79]:
a.dtype # a's common element type (A.dtype is undefined!)

dtype('float64')

In [80]:
2*a #Multiplication happen inside array

array([0.2, 2.6, 0.8, 1. ])

In [81]:
2*A #making another copy of elements for lists

[0.1, 1.3, 0.4, 0.5, 0.1, 1.3, 0.4, 0.5]

In [82]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [83]:
# list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]
# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)


57.5 ms ± 6.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
6.57 ms ± 2.34 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


we can see that numpy's ufuncs are relatively faster

#vectorization

In [84]:
def f(v): # apply f to one scalar value v
  return math.sin(v) * math.exp(-v)


In [85]:
vectorizedf = map(f, x) # apply same f to a vector of values x

In [86]:
F = np.vectorize(f) # F can be applied to a array x


In [87]:
# use map
%timeit y = list(map(f, x))
# use numpy's vectorize
%timeit y = F(x)
# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

55.8 ms ± 30.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
36.2 ms ± 705 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.31 ms ± 697 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [88]:
%timeit for x in range(1000000): x**3
%timeit for x in np.arange(1000000): x**3

349 ms ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
148 ms ± 32.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [89]:
a = np.random.randint(0,9,5) #generating a 5 elemented random arrays  from set mentioned
a

array([0, 7, 0, 6, 7])

In [90]:
a[::] #whole array

array([0, 7, 0, 6, 7])

In [91]:
a[-3:] #last 3 elemments

array([0, 6, 7])

In [92]:
a[-1], a[len(a)-1] #both denotes last element in array

(7, 7)

In [93]:
a[-4:-1:2] #4th last to last with gap of 2

array([7, 6])

In [94]:
slice = range(-4,-1,2)
# Think of b:e:s specification as a range.
a[-4:-1:2], a[slice]

(array([7, 6]), array([7, 6]))

In [95]:
a = np.array([1,2,3])
b = np.array([3,4,5,6])

In [96]:
a = b #a changes into b
a[0] = 1 #first element is made 1
a

array([1, 4, 5, 6])

In [97]:
b #we didn't change b

array([1, 4, 5, 6])

In [98]:
a = np.array([1,2,3]) # This is Object1 and "a" is a name for it.
b = np.array([3,4,5,6]) # This is Object2 and "b" is a name for it.

In [99]:
id(a), id(b)
#id denotes how its stored

(137828131991888, 137828131992752)

In [100]:
a = b # a is no longer a name for Object1, it is now a name for Object2.

In [101]:
id(a), id(b)

(137828131992752, 137828131992752)

In [102]:
a = np.array([1,2,3]) # Object1
b = np.array([3,4,5,6]) # Object2
a = b.copy() # Copies Object2, and binds a to the copy
a[0] = 2 # Only the copied (new) object is changed

In [103]:
a,b

(array([2, 4, 5, 6]), array([3, 4, 5, 6]))

In [104]:
Amat = [[1,2], [3,4]]
Amat

[[1, 2], [3, 4]]

In [105]:
amat = np.array(Amat)
amat #numpy array

array([[1, 2],
       [3, 4]])

In [106]:
type(A), type(a)

(list, numpy.ndarray)

In [107]:
2*Amat

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [108]:
2*amat

array([[2, 4],
       [6, 8]])

In [109]:
amat

array([[1, 2],
       [3, 4]])

In [110]:
amat*amat
#elementwise multiplication

array([[ 1,  4],
       [ 9, 16]])

In [111]:
import sys
print(sys.version) # check if you have version >= 3.5 before trying @

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]


In [112]:
amat @ amat #matrix multiplication

array([[ 7, 10],
       [15, 22]])

In [113]:
np.dot(amat, amat) # dot(A,B) = matrix A multiplied by matrix B

array([[ 7, 10],
       [15, 22]])

In [114]:
amat.dot(amat)

array([[ 7, 10],
       [15, 22]])

In [115]:
amat**2 # not equal to matrix power !!

array([[ 1,  4],
       [ 9, 16]])

In [116]:
np.linalg.matrix_power(amat, 2)

array([[ 7, 10],
       [15, 22]])

In [117]:
A = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [118]:
A[1, :], A[:, 2]

(array([2, 5, 5, 2]), array([5, 5, 8]))

In [119]:
A[:3:2, :3]

array([[7, 8, 5],
       [9, 6, 8]])

In [120]:
M = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
M

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [121]:
M.reshape(2, 6) # Just a different view of the same data

array([[7, 8, 5, 1, 2, 5],
       [5, 2, 9, 6, 8, 9]])

In [122]:
M.ravel() # The 1D data of M in row-major ordering

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [123]:
A = np.array(M, order='F')
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [124]:
A.ravel(order='A') # A's internal ordering is Fortran style

array([7, 2, 9, 8, 5, 6, 5, 5, 8, 1, 2, 9])

In [125]:
M.ravel(order='A') # M's internal ordering is default C-style

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [126]:
N = np.arange(25).reshape(5,5) #reshaping to 5*5
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [127]:
mask = (N>7) & (N<18) # validating condition that entry >7 and <18
mask

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [128]:
N[mask] #sorting masked elements

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [129]:
i, j = np.where(mask) # Returns i and j indices where mask[i,j] is True.
i, j # 1st True value of mask is at i[0],j[0], # 2nd True value of mask is at i[1],j[1], etc.

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3]), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2]))

In [130]:
data = np.random.randint(low=0, high=10, size=30) # 1D array

In [131]:
T2 = np.reshape(data, (6, 5)) # 2D array
T2

array([[5, 2, 3, 0, 4],
       [5, 6, 0, 7, 2],
       [1, 4, 3, 8, 2],
       [0, 6, 2, 4, 4],
       [0, 5, 2, 8, 5],
       [9, 1, 2, 4, 4]])

In [132]:
T3 = np.reshape(data, (2, 3, 5)) # 3D array

T3

array([[[5, 2, 3, 0, 4],
        [5, 6, 0, 7, 2],
        [1, 4, 3, 8, 2]],

       [[0, 6, 2, 4, 4],
        [0, 5, 2, 8, 5],
        [9, 1, 2, 4, 4]]])

In [133]:
print('T3 is a ', T3.ndim, 'dimensional array of shape ', T3.shape)
print('T2 is a ', T2.ndim, 'dimensional array of shape ', T2.shape)
print('data is a ', data.ndim, 'dimensional array of shape ', data.shape)

T3 is a  3 dimensional array of shape  (2, 3, 5)
T2 is a  2 dimensional array of shape  (6, 5)
data is a  1 dimensional array of shape  (30,)
